"""The research evidence base: verified records, honest fallback, and the page that shows them."""

from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from duty_of_care import evidence
from duty_of_care.main import app

KINDS = {"mechanism", "fiction", "contested", "guidance", "reviews"}
CLASSES = {
    "method_specificity", "framing_as_solution", "absence_of_help_seeking",
    "romanticisation", "repetition", "signposting_absence",
}


def test_every_record_is_cited_and_mapped() -> None:
    records = evidence.local_records()["records"]
    assert len(records) >= 14
    ids = [item["record_id"] for item in records]
    assert len(ids) == len(set(ids))
    for item in records:
        assert item["doi"] and item["pmid"] and item["year"] >= 2001, item["record_id"]
        assert item["kind"] in KINDS, item["record_id"]
        assert set(item["trigger_classes"]) <= CLASSES and item["trigger_classes"], item["record_id"]
        assert item["finding"] and item["relevance"], item["record_id"]
    # The disagreeing study must be present and mapped to the same classes as the studies it contests.
    contested = {item["record_id"]: set(item["trigger_classes"]) for item in records if item["kind"] == "contested"}
    assert contested["romer-2020-plos-one"] == contested["bridge-2019-jaacap"]


def test_evidence_is_empty_when_store_is_not_configured(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv(evidence.STORE_ENV, raising=False)
    assert evidence.evidence_for(["method_specificity"]) == []


def test_applicable_filters_by_class_and_caps(monkeypatch: pytest.MonkeyPatch) -> None:
    def result(record_id: str, classes: list[str]) -> dict:
        return {"document": {"id": record_id, "structData": {"record_id": record_id, "doi": "10.1/x", "finding": "f", "trigger_classes": classes}}}

    results = [result("a", ["repetition"]), result("b", ["method_specificity"]), result("c", ["method_specificity"]), result("d", ["method_specificity"]), result("e", ["method_specificity"])]
    picked = evidence._applicable(results, ["method_specificity"])
    assert [item["record_id"] for item in picked] == ["b", "c", "d"]


def test_evidence_endpoint_and_page() -> None:
    client = TestClient(app)
    body = client.get("/v1/evidence").json()
    assert body["data"]["count"] >= 14
    assert body["data"]["verified_on"]
    assert body["disclaimer"]
    page = client.get("/evidence")
    assert page.status_code == 200
    assert "call or text 988" in page.text
    assert "Nothing on this page was generated by a model" in page.text
