"""The research behind the guidance, retrieved the same way the guidance is.

A second Google Agent Search data store holds short, attributed research
records: what each study found, with its citation. When a note is raised, the
records that bear on its trigger classes are retrieved and attached, so a
writer sees not only *what* the guidance says but *why*, with the evidence
stated as it stands, including the studies that disagree. Nothing here is
generated by a model; the records are written from the published abstracts and
checked against Europe PMC.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from .grounding import _as_plain, _search_store

EVIDENCE_PATH = Path(__file__).resolve().parents[1] / "guidance" / "evidence.json"
STORE_ENV = "VERTEX_SEARCH_EVIDENCE_STORE"
MAX_PER_NOTE = 3


def configured() -> bool:
    return bool(os.getenv(STORE_ENV))


def local_records() -> list[dict[str, Any]]:
    return json.loads(EVIDENCE_PATH.read_text("utf-8"))


def _applicable(results: list[dict[str, Any]], trigger_classes: list[str]) -> list[dict[str, Any]]:
    wanted = set(trigger_classes)
    records: list[dict[str, Any]] = []
    seen: set[str] = set()
    for result in results:
        document = result.get("document", {})
        data = _as_plain(document.get("structData", {}))
        record_id = str(data.get("record_id", document.get("id", "")))
        if record_id in seen or not data.get("doi") or not data.get("finding"):
            continue
        if not wanted.intersection(str(item) for item in data.get("trigger_classes", [])):
            continue
        seen.add(record_id)
        records.append(dict(data))
        if len(records) >= MAX_PER_NOTE:
            break
    return records


def evidence_for(trigger_classes: list[str]) -> list[dict[str, Any]]:
    """Research records for these trigger classes, via Agent Search; empty if not configured."""
    if not configured() or not trigger_classes:
        return []
    query = (
        "research evidence on screen and media portrayal of suicide for "
        + ", ".join(sorted(set(trigger_classes)))
    )
    results = _search_store(os.environ[STORE_ENV], query, 25)
    return _applicable(results, sorted(set(trigger_classes)))
